name: "Install Build Tools"
description: |
  Search for the dotfile and install it
  Available languages:
    - maven
    - java
    - node
    - python

runs:
  using: composite
  steps:
    - name: Check dotfile
      id: check-dotfile-lang
      uses: rhattox-shared-actions/shared-actions/actions/tools/dotfile@main

    - name: Install Maven
      if: steps.check-dotfile-lang.outputs.maven == 'true'
      uses: rhattox-shared-actions/shared-actions/actions/tools/maven@main

    - name: Install Java
      if: steps.check-dotfile-lang.outputs.java == 'true'
      uses: rhattox-shared-actions/shared-actions/actions/tools/java@main

    - name: Install node
      if: steps.check-dotfile-lang.outputs.java == 'true'
      uses: rhattox-shared-actions/shared-actions/actions/tools/node@main

    - name: Install python
      if: steps.check-dotfile-lang.outputs.java == 'true'
      uses: rhattox-shared-actions/shared-actions/actions/tools/python@main
