name: Package Helm Chart
description: Package a Helm chart

inputs:
  HELM_CHART_PATH:
    description: The path to the Helm chart - file not included
    required: true
    default: ./
  APPLICATION_VERSION:
    description: The version of the application to deploy
    required: true

runs:
  using: "composite"
  steps:
    - name: Get NodeJs App Version
      id: get-version
      shell: bash
      run: |
        #!/usr/bin/env bash
        set -euo pipefail

        rm -rf .cr-release-packages
        mkdir -p .cr-release-packages
        helm package ${{ inputs.HELM_CHART_PATH }} --app-version=${{ inputs.APPLICATION_VERSION }}  --version=${{ inputs.APPLICATION_VERSION }} --destination .cr-release-packages
