name: Upload Artifact
description: Upload an artifact to the workflow run

inputs:
  ARTIFACT_NAME:
    description: The name of the artifact
    required: true
  ARTIFACT_PATH:
    description: The path of the artifact
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
