name: Compute Github Tag
description: Check for the latest tag in the repository and compute the next version based on the current version and the latest tag.
inputs:
  APPLICATION_VERSION:
    required: true
    description: Application version to build
    default: ./
  GIT_TAG_LIST:
    required: true
    description: List of git tags to use for versioning

runs:
  using: "composite"
  steps:
    - name: Compute Github Tag
      shell: bash
      run: |
        #!/usr/bin/env bash
        set -euo pipefail

        echo "APPLICATION_VERSION=${{ inputs.APPLICATION_VERSION }}"
        echo "GIT_TAG_LIST=${{ inputs.GIT_TAG_LIST }}"


        if [ -z "$GIT_TAG_LIST" ] || [ "$(echo "$GIT_TAG_LIST" | jq length)" -eq 0 ]; then
          echo "The JSON is empty."
        else
          echo "The JSON is not empty."
        fi
