name: Github Tag
description: Github Tag

outputs:
  GIT_TAG_LIST:
    description: A JSON array of all Git tags in the repository.
    value: ${{ steps.get-git-tags.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: Get all Git tags
      shell: bash
      id: get-git-tags
      run: |
        #!/usr/bin/env bash
        set -euo pipefail

        # Fetch all tags from the remote
        git fetch --tags

        tag=$(git describe --tags --abbrev=0 || echo "error")
        echo "tag=${tag}" 
        echo "tag=${tag}" >> $GITHUB_OUTPUT
