name: Java Installer
description: Java Central Installer

inputs:
  java-version:
    required: true
    description: java version
  distribution:
    required: true
    description: java distribution

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v5
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}
