name: Configure User for Git
description: Configure Git user for the action

runs:
  using: "composite"
  steps:
    - name: Configure Git User
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
