name: Checkout Extra with Git Branch, Git Token and Github Repository
description: Checkout a Git repository with a specific branch and token
inputs:
  GHA_TOKEN:
    description: Token to authenticate with the repository
    required: true
  GHA_BRANCH:
    description: Branch to checkout
    required: true
    default: main
  GHA_REPOSITORY:
    description: Branch to checkout
    required: true
    default: main

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: "${{ inputs.GHA_REPOSITORY }}"
        ref: "${{ inputs.GHA_BRANCH }}"
        token: ${{ inputs.GHA_TOKEN }}

    - name: Set Git safe directory
      shell: sh
      run: git config --global --add safe.directory "/__w/${{ github.event.repository.name }}"
