name: Login to DockerHub Container Registry
description: Login to DockerHub Container Registry

inputs:
  DOCKER_USERNAME:
    required: true
    description: The username for DockerHub
  DOCKER_TOKEN:
    required: true
    description: The token for DockerHub

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ inputs.DOCKER_TOKEN }}
