name: Deploy ArgoCD

on:
  workflow_call:
    inputs:
      APPLICATION_VERSION:
        required: true
        type: string
        description: The version of the application to deploy

jobs:
  deploy:
    timeout-minutes: 2
    name: Deploy version to ArgoCD
    runs-on: self-hosted
    container:
      image: bcovies/toolbox:0.0.1
    steps:
      - name: Checkout Repository
        uses: rhattox-shared-actions/shared-actions/actions/etc/checkout@main

      - name: Commit Version and Push Changes
        uses: rhattox-shared-actions/shared-actions/actions/etc/argocd/deploy-new-image@main
        with:
          APPLICATION_VERSION: ${{ inputs.APPLICATION_VERSION }}
