name: Build and Push Docker Image to DockerHub

on:
  workflow_call:
    inputs:
      APPLICATION_VERSION:
        required: true
        type: string
        description: The version of the application to deploy
      APPLICATION_NAME:
        required: true
        type: string
        description: The name of the application to deploy
      GHA_BRANCH:
        required: false
        type: string
        description: The branch to checkout
        default: main
    secrets:
      GHA_TOKEN:
        required: true
        description: Token to authenticate with the repository
      DOCKER_USERNAME:
        required: true
        description: DockerHub username
      DOCKER_TOKEN:
        required: true
        description: DockerHub token

jobs:
  convert-version:
    if: |
      github.ref != 'refs/heads/main'
    timeout-minutes: 1
    name: Convert version to tag
    runs-on: self-hosted
    container:
      image: bcovies/helm-toolbox:0.0.3
    outputs:
      APPLICATION_VERSION: ${{ steps.set-version.outputs.APPLICATION_VERSION }}
    steps:
      - name: Set version to tag
        id: set-version
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/feature/* ]]; then
            echo "APPLICATION_VERSION=${{ inputs.APPLICATION_VERSION }}-${{ github.ref_name }}-${{ github.sha }}"
            echo "APPLICATION_VERSION=${{ inputs.APPLICATION_VERSION }}-${{ github.ref_name }}-${{ github.sha }}" >> $GITHUB_OUTPUT
          else
            echo "APPLICATION_VERSION=${{ inputs.APPLICATION_VERSION }}" 
            echo "APPLICATION_VERSION=${{ inputs.APPLICATION_VERSION }}" >> $GITHUB_OUTPUT
          fi

  build-and-push:
    needs: convert-version
    if: |
      github.ref != 'refs/heads/main'
    timeout-minutes: 7
    name: Builds and Push Docker image
    runs-on: self-hosted
    container:
      image: docker:28-cli
    steps:
      - name: Checkout Repository
        uses: rhattox-shared-actions/shared-actions/actions/git/checkout@main
        with:
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
          GHA_REPOSITORY: ${{ github.repository }}
          GHA_BRANCH: ${{ inputs.GHA_BRANCH }}

      - name: Login DockerHub
        uses: rhattox-shared-actions/shared-actions/actions/docker/login@main
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        uses: rhattox-shared-actions/shared-actions/actions/docker/build@main
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_IMAGE_NAME: ${{ inputs.APPLICATION_NAME }}
          DOCKER_IMAGE_TAG: ${{ needs.convert-version.outputs.APPLICATION_VERSION }}

      - name: Push Docker image
        uses: rhattox-shared-actions/shared-actions/actions/docker/push@main
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_IMAGE_NAME: ${{ inputs.APPLICATION_NAME }}
          DOCKER_IMAGE_TAG: ${{ needs.convert-version.outputs.APPLICATION_VERSION }}

  deploy-argocd:
    needs: [build-and-push, convert-version]
    if: |
      startsWith(github.ref, 'refs/heads/feature/')
    name: Deploy version to ArgoCD
    uses: rhattox-shared-actions/shared-actions/.github/workflows/argocd-deploy.yaml@main
    secrets:
      GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
    with:
      APPLICATION_VERSION: ${{ needs.convert-version.outputs.APPLICATION_VERSION }}
      GHA_BRANCH: ${{ inputs.GHA_BRANCH }}
