name: Build and Push Docker Image to DockerHub

on:
  workflow_call:
    inputs:
      APPLICATION_VERSION:
        required: true
        type: string
        description: The version of the application to deploy

jobs:
  convert-version:
    timeout-minutes: 1
    name: Convert version to tag
    runs-on: self-hosted
    container:
      image: bcovies/helm-toolbox:0.0.3
    steps:
      - name: Set version to tag
        run: echo "APPLICATION_VERSION=${{ inputs.APPLICATION_VERSION }}" >> $GITHUB_ENV

  build-and-push:
    needs: convert-version
    if: |
      startsWith(github.ref, 'refs/heads/feature/') ||
      startsWith(github.ref, 'refs/tags/')
    timeout-minutes: 7
    name: Builds and Push Docker image
    runs-on: self-hosted
    container:
      image: docker:28-cli
    steps:
      - name: Checkout Repository
        uses: rhattox-shared-actions/shared-actions/actions/git/checkout@main
        with:
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
          GHA_REPOSITORY: ${{ github.repository }}
          GHA_BRANCH: main

      - name: Login DockerHub
        uses: rhattox-shared-actions/shared-actions/actions/docker/login@main
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        uses: rhattox-shared-actions/shared-actions/actions/docker/build@main
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_IMAGE_NAME: ${{ inputs.APPLICATION_NAME }}
          DOCKER_IMAGE_TAG: ${{ inputs.APPLICATION_VERSION }}

      - name: Push Docker image
        uses: rhattox-shared-actions/shared-actions/actions/docker/push@main
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_IMAGE_NAME: ${{ inputs.APPLICATION_NAME }}
          DOCKER_IMAGE_TAG: ${{ inputs.APPLICATION_VERSION }}

  deploy-argocd:
    needs: [build-and-push, convert-version]
    if: |
      startsWith(github.ref, 'refs/heads/feature/')
    name: Deploy version to ArgoCD
    uses: rhattox-shared-actions/shared-actions/.github/workflows/argocd-deploy.yaml@main
    secrets:
      GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
    with:
      APPLICATION_VERSION: ${{ inputs.APPLICATION_VERSION }}
