name: Create Git Tag

on:
  workflow_call:
    inputs:
      version:
        description: "Version tag to create (e.g., v1.2.3)"
        required: true
        type: string
    secrets:
      GHA_TOKEN:
        required: true
        description: Token to authenticate with the repository
jobs:
  create-tag:
    timeout-minutes: 1
    name: Create Git Tag
    runs-on: self-hosted
    container:
      image: bcovies/helm-toolbox:0.0.3

    steps:
      - name: Checkout Repository
        uses: rhattox-shared-actions/shared-actions/actions/git/checkout@main
        with:
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
          GHA_REPOSITORY: ${{ github.repository }}
          GHA_BRANCH: main

      - name: Create Git Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}

      - name: Zip source code
        run: |
          zip -r source-code-${{ inputs.version }}.zip . -x '.git/*'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          files: source-code-${{ inputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_TOKEN }}
