name: Github Tag Workflow

on:
  workflow_call:
    inputs:
      APPLICATION_VERSION:
        required: false
        description: Application version to build
        type: string
    secrets:
      GHA_TOKEN:
        required: true
        description: Token to authenticate with the repository

jobs:
  nodejs-preflight:
    timeout-minutes: 10
    name: Github Tag Setup
    runs-on: self-hosted
    container:
      image: bcovies/toolbox:0.0.1

    steps:
      - name: Checkout Repository
        uses: rhattox-shared-actions/shared-actions/actions/git/checkout@main
        with:
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}

      - name: Get Git Tags
        id: git-get-tags
        uses: rhattox-shared-actions/shared-actions/actions/git/list-tags@main

      - name: Compute Git Tags
        uses: rhattox-shared-actions/shared-actions/actions/git/compute-tags@main
        with:
          APPLICATION_VERSION: ${{ inputs.APPLICATION_VERSION }}
          GIT_TAG_LIST: ${{ steps.git-get-tags.outputs.GIT_TAG_LIST }}

      - name: Create Git Tags
        uses: rhattox-shared-actions/shared-actions/actions/git/create-tags@main
        with:
          APPLICATION_VERSION: ${{ inputs.APPLICATION_VERSION }}

      - name: Delete Git Tags
        uses: rhattox-shared-actions/shared-actions/actions/git/create-tags@main
