name: Github Tag Workflow

on:
  workflow_call:
    inputs:
      APPLICATION_VERSION:
        required: false
        description: Application version to build
        type: string
    secrets:
      GHA_TOKEN:
        required: true
        description: Token to authenticate with the repository

jobs:
  github-tag-setup:
    timeout-minutes: 10
    name: Github Tag Setup
    runs-on: self-hosted
    container:
      image: bcovies/toolbox:0.0.3

    steps:
      - name: Checkout Repository
        uses: rhattox-shared-actions/shared-actions/actions/git/checkout@main
        with:
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}

      - name: Get Git Tag
        id: git-get-tag
        uses: rhattox-shared-actions/shared-actions/actions/git/list-tag@main

      - name: Compute Git Tag
        uses: rhattox-shared-actions/shared-actions/actions/git/compute-tag@main
        with:
          APPLICATION_VERSION: ${{ inputs.APPLICATION_VERSION }}
          GIT_TAG_LIST: ${{ steps.git-get-tag.outputs.GIT_TAG_LIST }}

      - name: Create Git Tag
        uses: rhattox-shared-actions/shared-actions/actions/git/create-tag@main
        with:
          APPLICATION_VERSION: ${{ inputs.APPLICATION_VERSION }}

      - name: Delete Git Tag
        uses: rhattox-shared-actions/shared-actions/actions/git/delete-tag@main
