name: Helm Chart CI/CD

on:
  workflow_call:
    inputs:
      HELM_CHART_PATH:
        type: string
        required: true
    secrets:
      GHA_TOKEN:
        required: true
        description: Token to authenticate with the repository

jobs:
  helm-package:
    if: startsWith(github.ref, 'refs/tags/')
    timeout-minutes: 10
    name: Helm Package
    runs-on: self-hosted
    container:
      image: bcovies/helm-toolbox:0.0.3

    steps:
      - name: Checkout Repository
        uses: rhattox-shared-actions/shared-actions/actions/git/checkout@main
        with:
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
          GHA_REPOSITORY: ${{ github.repository }}
          GHA_BRANCH: main

      - name: Helm lint
        uses: rhattox-shared-actions/shared-actions/actions/helm/lint@main
        with:
          HELM_CHART_PATH: ${{ inputs.HELM_CHART_PATH }}

      - name: Helm Get Version
        id: get-version
        uses: rhattox-shared-actions/shared-actions/actions/helm/get-version@main
        with:
          HELM_CHART_PATH: ${{ inputs.HELM_CHART_PATH }}

      - name: Helm Package
        uses: rhattox-shared-actions/shared-actions/actions/helm/package@main
        with:
          HELM_CHART_PATH: ${{ inputs.HELM_CHART_PATH }}
          APPLICATION_VERSION: ${{ steps.get-version.outputs.APPLICATION_VERSION }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_packaging: true
          charts_dir: ${{ inputs.HELM_CHART_PATH }}
        env:
          CR_TOKEN: "${{ secrets.GHA_TOKEN }}"
