name: Helm Chart CI/CD

on:
  workflow_call:
    inputs:
      HELM_CHART_PATH:
        type: string
        required: true
      GITHUB_PAGES_BRANCH:
        type: string
        required: false
        default: gh-pages
    secrets:
      GHA_TOKEN:
        required: true
        description: Token to authenticate with the repository

jobs:
  helm-package:
    timeout-minutes: 10
    name: Helm Package
    runs-on: self-hosted
    container:
      image: bcovies/helm-toolbox:0.0.3

    steps:
      - name: Checkout Repository
        uses: rhattox-shared-actions/shared-actions/actions/git/checkout@main
        with:
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
          GHA_REPOSITORY: ${{ github.event.repository.name }}
          GHA_BRANCH: main

      - name: Helm lint
        uses: rhattox-shared-actions/shared-actions/actions/helm/lint@main
        with:
          HELM_CHART_PATH: ${{ inputs.HELM_CHART_PATH }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: ${{ inputs.HELM_CHART_PATH }}
        env:
          CR_TOKEN: "${{ secrets.GHA_TOKEN }}"

      # - name: Helm Package
      #   uses: rhattox-shared-actions/shared-actions/actions/helm/package@main
      #   with:
      #     HELM_CHART_PATH: ${{ inputs.HELM_CHART_PATH }}

      # - name: Checkout gh-pages branch
      #   uses: actions/checkout@v4
      #   with:
      #     ref: ${{ inputs.GITHUB_PAGES_BRANCH }}
      #     path: ${{ inputs.GITHUB_PAGES_BRANCH }}
      #     token: ${{ secrets.GHA_TOKEN }}

      # - name: Update Helm repo index
      #   run: |
      #     cd gh-pages
      #     cp ../packaged/*.tgz .
      #     helm repo index . --url https://rhattox-helm-charts.github.io/${{ github.repository }}

      # - name: Commit and push to gh-pages
      #   run: |
      #     cd gh-pages
      #     git config user.name "github-actions"
      #     git config user.email "github-actions@github.com"
      #     git add .
      #     git commit -m "Update Helm charts" || echo "No changes to commit"
      #     git push
