name: Checkout
description: Check out a repository
inputs:
  GHA_TOKEN:
    description: Token to authenticate with the repository
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.GHA_TOKEN }}

    - name: Set Git safe directory
      shell: bash
      run: git config --global --add safe.directory "/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}"
